name: Deploy to Fly
on: [push]
jobs:
  deploy:
    name: Deploy fiszki
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_CONTENT }} > "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
      - uses: superfly/flyctl-actions@master
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GOOGLE_APPLICATION_CREDENTIALS:  ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: "deploy"
