name: Deploy to Fly
on: [push]
jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: npm install
      - run: npm test
        env:
          CI: true

  deploy:
    name: Deploy to fiszki.fly.dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --env PORT='8080'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
